name: Django CI/CD – Deploy to Heroku

on:
  push:
    branches: [ main, deploy ]
  pull_request:
    branches: [ main, deploy ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: project_recipe.settings
      PYTHON_VERSION: "3.12"
      PIP_CACHE_DIR: ~/.cache/pip

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django tests
        env:
          SECRET_KEY: "dummy-secret-key-for-ci"
        run: |
          python manage.py migrate --noinput
          python manage.py test

      - name: Deploy to Heroku
        if: github.event_name == 'push'
        uses: akhileshns/heroku-deploy@v4.4.8
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email:    ${{ secrets.HEROKU_EMAIL }}
          strategy: api
          check_status: true
          usedocker: false

      - name: Show deployment URL
        if: github.event_name == 'push'
        run: |
          echo "Deployed to: https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com" >> "$GITHUB_STEP_SUMMARY"